[
{"moduleId":"maps4all/mapquest"},
{"moduleId":"mapman100/Here"},
{"moduleId":"coolmapper01/ca-gov"},
{"moduleId":"jamesbond002/osm"},
{"moduleId":"wazemap/waze"},
{"moduleId":"wazemap/wikimap"},
{"moduleId":"grabowCommuter/Speedometer"}
]
